version: '3'

services:
    db:
      image: postgres
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      env_file:
        - ./.env.db.prod

    web:
      build: .
      restart: always
      command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/code
        - static_volume:/code/staticfiles
      expose:
        - "8000"
      env_file:
        - ./.env.prod
      depends_on:
        - db
    nginx:
      build: ./nginx
      volumes:
        - static_volume:/code/staticfiles
      ports:
        - 1337:80
      depends_on:
        - web

volumes:
  static_volume:
  postgres:
  